# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2019

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  About: /about
  Resume: /resume

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  Categories: true

widget_custom:
    title:
    content:

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

math:
  enable: true
  engine: mathjax

highlight:
  enable: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Analytics
baidu_analytics:
google_analytics:

# Site Verification
google_site_verification:
naver_site_verification:

# Disqus
disqus_shortname:

# ===========================================
# Version
# ===========================================
version: 1.1
